### ISSUE TITLE
Support for spark DataFrames

### ISSUE THREAD

**Issue by raiviskrumins** [rendner/py-plugin-dataframe-viewer#3]
Works very well with pandas. Would be nice to use this plugin also for spark dataframes.

**Comment by rendner** [comment]
Thank you for your feedback.

I have no experience with Spark DataFrames, so I can't estimate how much work it would be to support another kind of DataFrame. I almost think that supporting two different projects is beyond my free time.

At the moment I already have the following features on my roadmap:
- Adding Filtering for pandas DataFrames
- Adding Support for pandas 1.5.0
- Adding Support for pandas 1.4.4 (if required)

So I'll be pretty busy until I can find some time to see if Spark can be supported in my available time.
I think before October it will not be possible.

**Comment by rendner** [comment]
I am closing this request for now as there has been no further feedback from other users.
